# Generated by Django 5.1 on 2024-08-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_rubric_clothingmodel_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothingmodel',
            options={'ordering': ['title'], 'verbose_name': 'Одежда'},
        ),
        migrations.AlterField(
            model_name='clothingmodel',
            name='desc',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='clothingmodel',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='clothingmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Название рубрики'),
        ),
    ]
